version: '3'
services:
  backend:
    image: blipblop/backend
    container_name: backend
    build: backend
    restart: always
    ports:
      - "80:8080"
    environment:
      - DB_DRIVER=sqlite3
      - DB_NAME=/prototype.db
